const fs = require('fs');
const path = require('path');

const directories = [
   'c:/Users/HP/Desktop/Campus Guide/src/components/guide/content/ucc',
   'c:/Users/HP/Desktop/Campus Guide/src/components/tools',
   'c:/Users/HP/Desktop/Campus Guide/src/pages',
];

directories.forEach(dir => {
   if (!fs.existsSync(dir)) return;
   const files = fs.readdirSync(dir);

   files.forEach(file => {
      if (!file.endsWith('.jsx')) return;
      const filePath = path.join(dir, file);
      let content = fs.readFileSync(filePath, 'utf8');

      // Standardize invalid tailwind generated by previous naive regexs

      // 1. Remove instances of multiple opacities like /60/60
      content = content.replace(/dark:([a-z0-9-]+)\/\d+\/\d+/g, 'dark:$1/60');
      content = content.replace(/dark:bg-gray-800\/60\/60/g, 'dark:bg-gray-800/60');
      content = content.replace(/dark:bg-gray-800\/40\/60/g, 'dark:bg-gray-800/50');

      // 2. Remove chained identical or conflicting dark variants on bg-white
      content = content.replace(/bg-white\s+(dark:bg-gray-[0-9]+\/(?:\d+)?\s*)+/g, 'bg-white dark:bg-gray-800/60 ');

      // 3. Remove duplicate dark text colors
      content = content.replace(/(dark:text-[a-z0-9-]+(?:\/\d+)?\s*){2,}/g, (match) => {
         // split by space, keep first
         return match.trim().split(/\s+/)[0] + ' ';
      });

      // 4. Remove duplicate dark bg colors
      content = content.replace(/(dark:bg-[a-z0-9-]+(?:\/\d+)?\s*){2,}/g, (match) => {
         // split by space, keep first
         return match.trim().split(/\s+/)[0] + ' ';
      });

      fs.writeFileSync(filePath, content);
   });
});

console.log('Cleanup complete');
